apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
type: Opaque
data:
  private: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ1VzY2d6Y3NQTEluMC9CT3oKbkE4RkFQaURkSjJDb0hTQmNVd2dNQjgvY1c2aFJBTkNBQVJtaENVa2dJdXZQejJMT2l1N1Y3WS9ESXJLM1NsdgpiU3JYOTRPVkFRd3pVVHdObUNidk1JVG43N0pFRVVaNXhvMFoxTnVzWUViTVpvbm12TnF3amdwegotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  public: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFWm9RbEpJQ0xyejg5aXpvcnUxZTJQd3lLeXQwcApiMjBxMS9lRGxRRU1NMUU4RFpnbTd6Q0U1Kyt5UkJGR2VjYU5HZFRickdCR3pHYUo1cnphc0k0S2N3PT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
