apiVersion: v1
kind: Service
metadata:
  name: composition-service
spec:
  ports:
    - port: 3000
      name: http
      protocol: TCP
  selector:
    app: composition
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: composition-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: composition
        version: 0.0.1
    spec:
      containers:
        - name: composition
          image: composition:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
            - name: APP_URL_POSTS
              value: http://posts-service:3000/posts
            - name: APP_URL_USERS
              value: http://users-service:3000/users
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: public
                  optional: false
  selector:
    matchLabels:
      app: composition
