apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: posts-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: posts-deployment
  targetCPUUtilizationPercentage: 30
status:
  currentReplicas: 1
  desiredReplicas: 0
